export const BaseEnvConfig = {
  PORT: 'PORT',
  POSTGRES_DB_HOST: 'POSTGRES_DB_HOST',
  POSTGRES_DB_PORT: 'POSTGRES_DB_PORT',
  POSTGRES_DB_USER: 'POSTGRES_DB_USER',
  POSTGRES_DB_PASSWORD: 'POSTGRES_DB_PASSWORD',
  DB_NAME: 'DB_NAME',
  TOKEN_EXPIRATION_TIME: 'TOKEN_EXPIRATION_TIME',
  TOKEN_SECRET: 'TOKEN_SECRET',
  REFRESH_TOKEN_EXPIRATION_TIME: 'REFRESH_TOKEN_EXPIRATION_TIME',
  REFRESH_TOKEN_SECRET: 'REFRESH_TOKEN_SECRET',
};
